model_params:
  model_seed: 1234
  name: 'ResAssortNN'
  Nprod_Veclen: 21

  Num_resBlock: 2
  Num_res_neckLayer: 0
  res_neckLayers: []




data_params:
  data_seed: 123

  data_path: "BCG_fake"

  Assortments: "ASSORT.npy"
  Final_choices: "SAMP.npy"


  train_amount: 150000

  valid_amount: 10000
  
  test_amount: 10000

  device: "gpu"


exp_params:
  exp_seed: 123


  train_batch_size: 1000
  valid_batch_size: 10000
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 1

  device: "gpu"
  max_epochs: 30


logging_params:

  log_name: "BCG_RES_NN_tune"

  log_save_perEpoch: 20

  log_save_stack: 4
