model_params:
  model_seed: 1234
  name: 'VanillaMNL'
  Nprod_Veclen: 21
  feature: False



data_params:
  data_seed: 123

  data_path: "BCG"

  Assortments: "ASSORT.npy"
  Final_choices: "SAMP.npy"


  train_amount: 10000

  valid_amount: 1000
  
  test_amount: 5000

  device: "gpu"


exp_params:
  exp_seed: 123


  train_batch_size: 5
  valid_batch_size: 1000
  LR: 0.0002
  weight_decay: 0.0
  scheduler_gamma: 1

  device: "gpu"
  max_epochs: 100


logging_params:

  log_name: "BCG_MNL"

  log_save_perEpoch: 20

  log_save_stack: 4
