model_params:
  model_seed: 1234
  name: 'AssortmentNN'
  Nprod_Veclen: 7

  Num_CrossEffectLayer: 1
  Cross_midLayers: [7]



data_params:
  data_seed: 1234

  data_path: "msom/H5"

  Assortments: "ASSORT.npy"
  Final_choices: "SAMP.npy"


  train_amount: 800

  valid_amount: 100
  
  test_amount: 100

  device: "gpu"


exp_params:
  exp_seed: 1234


  train_batch_size: 5
  valid_batch_size: 100
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.99

  device: "gpu"
  max_epochs: 200


logging_params:

  log_name: "H5_warm"

  log_save_perEpoch: 20

  log_save_stack: 4


