model_params:
  model_seed: 5634
  name: 'ResAssortNN'
  Nprod_Veclen: 12

  Num_resBlock: 1
  Num_res_neckLayer: 0
  res_neckLayers: []




data_params:
  data_seed: 1234

  data_path: "msom/H1"

  Assortments: "ASSORT.npy"
  Final_choices: "SAMP.npy"


  train_amount: 6000

  valid_amount: 1000
  
  test_amount: 1000

  device: "gpu"


exp_params:
  exp_seed: 1234


  train_batch_size: 20
  valid_batch_size: 1000
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 1

  device: "gpu"
  max_epochs: 50


logging_params:

  log_name: "Res1"

  log_save_perEpoch: 20

  log_save_stack: 4
